coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch:
      default:
        target: 40%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
