name: Bug report
description: Report an error or unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the fdsreader GitHub repository!
        We always appreciate feedback from our users.
        Please fill out as many fields as possible to help us reproduce the bug 
        more easily.

        Thank you for using fdsreader!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce this bug.
        If possible, please include a minimal, fully reproducible example or a link to a Git repository.
      placeholder: Put your code or a link here

  - type: textarea
    id: fds-version
    attributes:
      label: FDS version used
      description: Please tell us what FDS version was used.
      placeholder: Version 
    validations:
      required: true

  - type: textarea
    id: fdsreader-version
    attributes:
      label: fdsreader version used
      description: Please tell us what fdsreader version was used.
      placeholder: Version 
    validations:
      required: true

  - type: markdown
    attributes:
      value: "_Thanks for submitting this bug report!_"